name: CI

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws_access_key_id:     "${{ secrets.BUILD_LDS_AWS_ACCESS_KEY_ID }}"
          aws_secret_access_key: "${{ secrets.BUILD_LDS_AWS_SECRET_ACCESS_KEY }}"
          aws-region: "eu-west-1"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - uses: actions/checkout@v4

      - name: Build
        run: make image

      - name: Publish
        run: make publish
